### ISSUE TITLE
Missing Description & OG Info for HiveConf Website

### ISSUE THREAD

**Issue by VaniPillayHP** [honeypotio/hive-conf#7]
For the HiveConf'19 website, there is no description, so when you google HiveConf'19 just the words present on the landing page are shown as the description. There is also no Open Graph info, so when we try and link the website on facebook/other social media, a large photo of one of our speakers shows, not the proper cover photo from the website. 

1) Here is the description:

_“HiveConf is a one-day conference for HR & Talent Acquisition Leaders, Technical Hiring managers, CTOs and VPs of Engineering focused on all aspects of building & scaling great tech teams.”_

2. Here is example code of how to do the Open Graph Info (not sure about the react-helmet bit) :

<`meta data-react-helmet="true" property="og:type" content="website"/><meta data-react-helmet="true" property="og:title" content="HiveConf'19 - Where Tech meets HR"/><meta data-react-helmet="true" property="og:description" content="HiveConf is a one-day conference for HR & Talent Acquisition Leaders, Technical Hiring managers, CTOs and VPs of Engineering focused on all aspects of building & scaling great tech teams."/><meta data-react-helmet="true" property="og:image" content="INPUT IMAGE URL HERE, ASK BUGRA“/><meta data-react-helmet="true" property="og:image:alt" content="HiveConf'19 - Where Tech meets HR"/`>

3. Twitter needs an even more specific OG, so here is an example of the code:

<`meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:site" content=“@honeypotio”>
<meta name="twitter:title" content="HiveConf'19 - Where Tech meets HR">
<meta name="twitter:description" content="HiveConf is a one-day conference for HR & Talent Acquisition Leaders, Technical Hiring managers, CTOs and VPs of Engineering focused on all aspects of building & scaling great tech teams.">
<meta name="twitter:image" content=“INPUT IMAGE URL HERE, ASK BUGRA“`>

Please and thank you!

**Comment by m-mcaulay** [comment]
@VaniPillayHP, @bkantar would be great to have the images or image urls that need to go in the following:
content="INPUT IMAGE URL HERE, ASK BUGRA"
content="summary_large_image"

**Comment by m-mcaulay** [comment]
@bkantar can please confirm after checking that it is ok?

**Comment by m-mcaulay** [comment]
tested using Facebook sharing debugger, linkedIn post inspector, twitter card validator

**Comment by VaniPillayHP** [comment]
Everything looks good :) Thanks!

**Comment by bkantar** [comment]
All good!
